// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'your-web-api-key',
    appId: 'your-web-app-id',
    messagingSenderId: 'your-sender-id',
    projectId: 'fuel-flow-app',
    authDomain: 'fuel-flow-app.firebaseapp.com',
    storageBucket: 'fuel-flow-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwPlINWlsPHSg7VnAV8Rr-8TN-Nc-GqgE',
    appId: '1:1038834166136:android:83f48de74aae45abc8c08d',
    messagingSenderId: '1038834166136',
    projectId: 'fuelflow-11489',
    storageBucket: 'fuelflow-11489.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA63XEtnC13lTEc2KrqEoGASpq3T_Kl928',
    appId: '1:1038834166136:ios:ebad05bbc637f95ec8c08d',
    messagingSenderId: '1038834166136',
    projectId: 'fuelflow-11489',
    storageBucket: 'fuelflow-11489.firebasestorage.app',
    iosBundleId: 'com.example.fuelFlow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'your-macos-api-key',
    appId: 'your-macos-app-id',
    messagingSenderId: 'your-sender-id',
    projectId: 'fuel-flow-app',
    storageBucket: 'fuel-flow-app.appspot.com',
    iosBundleId: 'com.ignivex.fuel_flow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'your-windows-api-key',
    appId: 'your-windows-app-id',
    messagingSenderId: 'your-sender-id',
    projectId: 'fuel-flow-app',
    authDomain: 'fuel-flow-app.firebaseapp.com',
    storageBucket: 'fuel-flow-app.appspot.com',
  );
}